-- import "CoreLibs/3d"
-- import "CoreLibs/accelerometer"
-- import "CoreLibs/animation"
-- import "CoreLibs/animator"
import "CoreLibs/crank"
-- import "CoreLibs/easing"
-- import "CoreLibs/frameTimer"
import "CoreLibs/graphics"
-- import "CoreLibs/keyboard"
-- import "CoreLibs/logic"
-- import "CoreLibs/math"
-- import "CoreLibs/nineslice"
-- import "CoreLibs/object"
-- import "CoreLibs/qrcode"
-- import "CoreLibs/save"
-- import "CoreLibs/sprites"
-- import "CoreLibs/strict"
-- import "CoreLibs/string"
-- import "CoreLibs/timer"
-- import "CoreLibs/ui"
